# packages/cli/pyproject.toml
[project]
name = "schemahive-cli"
version = "0.1.0"
description = "Schemahive CLI: init, connect, scan, diff, approve, export"
requires-python = ">=3.10"
dependencies = [
  "typer>=0.12.0",
  "schemahive-core",   # resolved from workspace
  "schemahive-sdk-py", # resolved from workspace
]

[project.scripts]
schemahive = "schemahive_cli.__main__:main"

[tool.uv.sources]
schemahive-core = { workspace = true }
schemahive-sdk-py = { workspace = true }

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
